config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, :controllers => {:registrations => "registrations"}
  # resources :projects
  # resources :tasks
  resources :projects do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :projects, dependent: :destroy    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # rescue_from ActionController::RoutingError, :with => :my_error

  private

  def my_error
    redirect_to root_path, alert: "my Error"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    if user_signed_in?
      @projects = current_user.projects
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def show
    @project = Project.find_by_id(params[:id])
    @tasks = @project.tasks
  end

  def new
    @project = Project.new
  end

  def create
    project = Project.create(project_params)
    project.user_id = current_user.id
    if project.save
      redirect_to root_path()
      flash[:notice] = "Project was created"
    else
      redirect_to new_project_path()
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    project = Project.find(params[:id])
    if project.update(project_params)
      redirect_to root_path
    else
      redirect_to edit_project_path(project.id)
    end
  end

  def destroy
    project = Project.find_by_id(params[:id])
    if project.destroy
      redirect_to root_path
      flash[:Success] = "Project is deleted"
    else
      flash[:notice] = "Project is NOT deleted"
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :user_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit( :name, 
                                  :email, 
                                  :password, 
                                  :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit( :name, 
                                  :email, 
                                  :password, 
                                  :password_confirmation, 
                                  :current_password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def show
    @project = Project.find params[:project_id]
    @task = Task.find_by_id(params[:id])
  end

  def new
    @project = Project.find params[:project_id]
    @task = Task.new
  end

  def create
    task = Task.create(task_params)
    task.project_id = Project.find(params[:project_id]).id
    if task.save
      redirect_to project_path(params[:project_id])
      flash[:notice] = "Task was created"
    else
      flash[:notice] = "Task not created"
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    task = Task.find(params[:id])
    if task.update(task_params)
      redirect_to project_path(task.project_id)
    else
      redirect_to edit_project_task_path(task.id)
    end
  end

  def destroy
    task = Task.find_by_id(params[:id])
    # project_id = task.project_id
    if task.destroy
      redirect_to project_path(params[:project_id])
      flash[:Success] = "Task is deleted"
    else
      flash[:notice] = "Task is NOT deleted"
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
require 'navigation_helper.rb'

module ApplicationHelper
  include NavigationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper

  def collapsible_links_partial_path
    if user_signed_in?
      'layouts/navigation/collapsible_elements/signed_in_links'
    else
      'layouts/navigation/collapsible_elements/non_signed_in_links'
    end
  end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/_project.html.erb
<% projects.each do |project| %>
  <div class="col-sm-3 single-post-card" style="width: 35%; max-height: fit-content" id=<%= project_path(project.id) %>>
    <div class="card" style="overflow-wrap: break-word;">
      <b><h4><%= truncate(project.name, :length => 60) %></h4></b>
      <div class="posted-by">Project by <%= project.user.name %></div>
      <p><%= project.description %></p>
      <%= link_to "View Tasks", project_path(project.id), class: 'btn btn-primary' %>
      <%= link_to 'Edit', edit_project_path(project.id), :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="container">
  <div class="row">
    <div id="side-menu"  class="col-sm-3">
    </div><!-- side-menu -->
    <div id="main-content" class="col-sm-9">
      <h1>Projects</h1>
      <%= render "project", projects: @projects %>
    </div><!-- main-content -->
    <%= link_to "Add new project", new_project_path, :class => "navbar-brand" %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="row">
      <div class="col-sm-7">
        <%= render 'layouts/navigation/header' %>
      </div>
      <div class="col-sm-5">
        <%= render 'layouts/navigation/collapsible_elements' %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SketchbrahmaAssignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/navigation/_collapsible_elements.html.erb
<div class="collapse navbar-collapse navbar-right" id="navbar-collapsible-content">
  <ul class="nav navbar-nav ">
    <%= render collapsible_links_partial_path %>
  </ul>
</div>

app/views/layouts/navigation/_header.html.erb
<div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapsible-content" aria-expanded="false">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <a class="navbar-brand" href="/">Sketchbrahma Technologies</a>
</div>

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.erb
<li ><%= link_to 'Login', user_session_path %></li>
<li ><%= link_to 'Signup', new_user_registration_path %></li>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
<li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
<li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>

app/views/projects/_task.html.erb
<% tasks.each do |task| %>
  <div class="col-sm-3 single-post-card" id=<%= project_task_path(@project.id, task.id) %>>
    <div class="card">
      <h4><%= truncate(task.title, :length => 60) %></h4>
      Task of <%= @project.name %>
      <p><%= task.content %></p>
      <%= link_to "View", project_task_path(@project.id, task.id), class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-4 col-sm-4">
      <h3 class="text-center">Edit your project</h3>
      <%= bootstrap_form_with(model: @project, local: true) do |f| %>
        <%= f.text_field :name, label: "Name", placeholder: "name" %>
        <%= f.text_field :description, placeholder: "description" %>
        <%= f.submit "Update", :class => "btn btn-primary" %>
        <%= link_to "Back", root_path, :class => "btn btn-primary" %>
      <% end %>
     </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-4 col-sm-4">
      <h3 class="text-center">Create new project</h3>
      <%= bootstrap_form_with(model: @project, local: true) do |f| %>
        <%= f.text_field :name, label: "Name", placeholder: "name" %>
        <%= f.text_field :description, placeholder: "description" %>
        <%= f.submit "Save", :class => "btn btn-primary" %>
        <%= link_to "Back", root_path, :class => "btn btn-primary" %>
      <% end %>
     </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="container">
  <div class="row">
    <div id="side-menu"  class="col-sm-3">
    </div><!-- side-menu -->
    <div id="main-content" class="col-sm-9">
       <h1>Tasks</h1>
      <%= render "task", tasks: @tasks %>
    </div>
    <div>
      <%= link_to "Add new task", new_project_task_path(@project.id), :class => "navbar-brand" %>
      <%= link_to "Back", root_path, :class => "navbar-brand" %>
      <%= link_to 'Delete', project_path(@project.id), :class => "navbar-brand", method: 'delete', data: { confirm: 'Are you sure to delete project?', :class => "navbar-brand" } %>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-4 col-sm-4">
      <h3 class="text-center">Edit your task</h3>
      <%= bootstrap_form_with(model: @task, local: true, url: project_task_path(@task.id)) do |f| %>
        <%= f.text_field :title, label: "Title", placeholder: "Title" %>
        <%= f.text_field :content, placeholder: "description" %>
        <%= f.submit "Update", :class => "btn btn-primary" %>
        <%= link_to "Back", root_path, :class => "btn btn-primary" %>
      <% end %>
     </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-offset-4 col-sm-4">
      <h3 class="text-center">Create new task</h3>
      <%= bootstrap_form_with(model: @task, url: project_tasks_path(@project.id), local: true,) do |f| %>
        <%= f.text_field :title, label: "Name", placeholder: "name" %>
        <%= f.text_field :content, placeholder: "description" %>
        <%= f.submit "Save", :class => "btn btn-primary" %>
        <%= link_to "Back", root_path, :class => "btn btn-primary" %>
      <% end %>
     </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="row">
    <div id="side-menu"  class="col-sm-3">
    </div><!-- side-menu -->
    <div id="main-content" class="col-sm-9">
      <div class="col-sm-3 single-post-card" id=<%= project_task_path(@project.id, @task.id) %>>
        <div class="text">
          Title: <%= truncate(@task.title, :length => 60) %></h3>
          <p> Content: <%= @task.content %></p>
        </div>
      </div>
    </div>
      <%= link_to "Back", :back, :class => "navbar-brand" %>
      <%= link_to 'Edit', edit_project_task_path(@project.id, @task.id), :class => "navbar-brand" %>
      <%= link_to 'Delete', project_task_path(@project.id, @task.id), :class => "navbar-brand", method: 'delete', data: { confirm: 'Are you sure?', :class => "navbar-brand" } %>
  </div>
</div>